name: publish

on:
  push:
    branches: ["main"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Build and push
        run: |
          docker build . --tag ghcr.io/eliangerard/docker-cicd-tests:latest
          docker push ghcr.io/eliangerard/docker-cicd-tests:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to production"

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Connect to Server
        run: |
          sshpass -p ${{ secrets.SSH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Connected to server"
          cd /root/Public
          git pull
          docker-compose down
          docker-compose up -d
